# Generated by Django 3.0.7 on 2020-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200902_1953'),
        ('orders', '0003_auto_20200902_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('provider', 'order')},
        ),
    ]
