# Generated by Django 3.0.7 on 2020-09-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_provides'),
        ('orders', '0007_auto_20200903_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='provides',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Provides'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('provides', 'order')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='provider',
        ),
    ]
