# Generated by Django 3.0.7 on 2020-09-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200902_2214'),
        ('basic', '0004_auto_20200902_1953'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date_time', models.DateTimeField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.Service_Provider')),
            ],
            options={
                'unique_together': {('provider', 'order_item')},
            },
        ),
    ]
