# Generated by Django 3.0.7 on 2020-09-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_remove_service_provider_service_category'),
        ('services', '0003_auto_20200903_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Service_Provider')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service_Category')),
            ],
        ),
    ]
