# Generated by Django 3.0.7 on 2020-09-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20200906_0148'),
        ('services', '0004_provides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provides',
            options={'ordering': ['provider'], 'verbose_name_plural': 'Provides'},
        ),
        migrations.AlterModelOptions(
            name='service_category',
            options={'ordering': ['service'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Service_Provider'),
        ),
    ]
