# Generated by Django 3.0.7 on 2020-09-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20200906_0148'),
        ('services', '0005_auto_20200906_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.Service_Provider'),
        ),
    ]
