# Generated by Django 3.0.7 on 2020-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200906_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='cost_per_unit',
            field=models.CharField(choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='Hour', max_length=20),
        ),
    ]
