# Generated by Django 3.0.7 on 2020-09-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200903_1853'),
        ('basic', '0004_auto_20200902_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service_Category'),
        ),
    ]
