# Generated by Django 3.0.7 on 2020-09-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_service_provider_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_provider',
            name='service_category',
        ),
    ]
