# Generated by Django 3.0.7 on 2020-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200904_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
