# Generated by Django 3.0.7 on 2020-09-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20200904_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_provider',
            options={'verbose_name_plural': 'Service Providers'},
        ),
    ]
